const {app,BrowserWindow,ipcMain,dialog,safeStorage}=require('electron');
const path=require('path');const fs=require('fs');const TronWeb=require('tronweb');
const DEFAULT_NODE='https://api.trongrid.io';let win;let pendingWin=null;let cfg;
function configPath(){return path.join(app.getPath('userData'),'config.json')}
function loadCfg(){try{cfg=JSON.parse(fs.readFileSync(configPath(),'utf8'));if(cfg.apiKeyEncrypted&&safeStorage.isEncryptionAvailable())cfg.apiKey=safeStorage.decryptString(Buffer.from(cfg.apiKeyEncrypted,'base64'));}catch{cfg={serverUrl:'',nodeUrl:DEFAULT_NODE,network:'mainnet',role:'AB',apiKey:'',signerA:'',signerB:'',cAddress:'',watchAddress:''}}}
function saveCfg(){fs.mkdirSync(path.dirname(configPath()),{recursive:true});const out={...cfg};delete out.apiKey;if(cfg.apiKey&&safeStorage.isEncryptionAvailable())out.apiKeyEncrypted=safeStorage.encryptString(String(cfg.apiKey)).toString('base64');fs.writeFileSync(configPath(),JSON.stringify(out,null,2),{mode:0o600})}
function tron(){return new TronWeb({fullHost:cfg.nodeUrl||DEFAULT_NODE})}
function assertKey(k){if(!/^[0-9a-fA-F]{64}$/.test(String(k||'')))throw Error('Private key must be 32-byte hex')}
async function recentIncoming(address,sinceMs=Date.now()-86400000,limit=200){if(!tron().isAddress(address))throw Error('Invalid address');const r=await tron().getEventResult?null:null;return {address,sinceMs,limit,items:r||[]}}
app.whenReady().then(()=>{loadCfg();win=new BrowserWindow({width:1280,height:900,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});win.loadFile(path.join(__dirname,'index.html'))});

ipcMain.handle('pending:show',async(_,r)=>{if(win&&!win.isDestroyed()){try{win.setAlwaysOnTop(true,'floating');win.setClosable(false);win.setMinimizable(false);win.focus();}catch{}return true}return false});
ipcMain.handle('pending:later',async()=>{if(win&&!win.isDestroyed()){try{win.setAlwaysOnTop(false);win.setClosable(true);win.setMinimizable(true);win.focus();}catch{}}return true});
ipcMain.handle('config:get',()=>cfg);ipcMain.handle('config:set',(_,p)=>{cfg={...cfg,...p};saveCfg();return cfg});
ipcMain.handle('tron:validate-address',(_,a)=>tron().isAddress(a));
ipcMain.handle('tron:permissions',async(_,a)=>{if(!tron().isAddress(a))throw Error('Invalid TRON address');const x=await tron().trx.getAccount(a);return{address:a,owner_permission:x.owner_permission||null,witness_permission:x.witness_permission||null,active_permission:x.active_permission||[]}});
ipcMain.handle('tron:build-permission-update',async(_,p)=>tron().transactionBuilder.updateAccountPermissions(p.targetAddress,p.owner,null,p.actives));
ipcMain.handle('tron:sign',async(_,p)=>{assertKey(p.privateKey);const t=new TronWeb({fullHost:cfg.nodeUrl||DEFAULT_NODE,privateKey:p.privateKey});const address=t.address.fromPrivateKey(p.privateKey);if(p.expectedAddress&&address.toLowerCase()!==p.expectedAddress.toLowerCase())throw Error('Private key does not match expected signer');return{address,transaction:await t.trx.multiSign(p.transaction,p.privateKey,Number(p.permissionId||0))}});
ipcMain.handle('tron:get-sign-weight',(_,t)=>tron().trx.getSignWeight(t));ipcMain.handle('tron:broadcast',(_,t)=>tron().trx.sendRawTransaction(t));
ipcMain.handle('tron:permission-preflight',async(_,p)=>{if(!tron().isAddress(p.targetAddress))throw Error('Invalid target C address');const x=await tron().trx.getAccount(p.targetAddress);if(x.witness_permission)throw Error('SR/Witness account is not supported in this version; fail closed');const owner=x.owner_permission;if(!owner)throw Error('C current Owner permission missing');const find=a=>Number((owner.keys||[]).find(k=>String(k.address).toLowerCase()===String(a).toLowerCase())?.weight||0);const aw=find(p.signerA),bw=find(p.signerB),th=Number(owner.threshold);if(aw<=0||bw<=0||aw+bw<th)throw Error(`A+B current Owner weight insufficient: ${aw}+${bw} < ${th}`);return {owner,active_permission:x.active_permission||[],aWeight:aw,bWeight:bw,threshold:th};});
ipcMain.handle('tron:execute-permission-update',async(_,p)=>{assertKey(p.privateKeyA);assertKey(p.privateKeyB);if(!tron().isAddress(p.targetAddress)||!tron().isAddress(p.signerA)||!tron().isAddress(p.signerB))throw Error('Invalid address');if(p.signerA.toLowerCase()===p.signerB.toLowerCase())throw Error('A/B cannot be same');const pre=await tron().trx.getAccount(p.targetAddress);if(pre.witness_permission)throw Error('SR/Witness account is not supported; fail closed');const find=a=>Number((pre.owner_permission?.keys||[]).find(k=>String(k.address).toLowerCase()===String(a).toLowerCase())?.weight||0);if(find(p.signerA)<=0||find(p.signerB)<=0||find(p.signerA)+find(p.signerB)<Number(pre.owner_permission?.threshold))throw Error('A+B cannot authorize current Owner permission');const wa=tron().address.fromPrivateKey(p.privateKeyA),wb=tron().address.fromPrivateKey(p.privateKeyB);if(wa.toLowerCase()!==p.signerA.toLowerCase()||wb.toLowerCase()!==p.signerB.toLowerCase())throw Error('Private key does not match A/B');const tx=await tron().transactionBuilder.updateAccountPermissions(p.targetAddress,p.proposedPermission.owner,null,p.proposedPermission.actives);const s1=await tron().trx.multiSign(tx,p.privateKeyA,0);const s2=await tron().trx.multiSign(s1,p.privateKeyB,0);const sw=await tron().trx.getSignWeight(s2);if(String(sw?.result?.code||'')!=='ENOUGH_PERMISSION')throw Error(`getSignWeight failed: ${JSON.stringify(sw?.result||sw)}`);const br=await tron().trx.sendRawTransaction(s2);if(!br?.result)throw Error(`Broadcast failed: ${JSON.stringify(br)}`);return {transaction:s2,broadcast:br,signers:[wa,wb],signWeight:sw};});ipcMain.handle('dialog:error',async(_,m)=>{await dialog.showMessageBox(win,{type:'error',title:'TRON Permission Control V5',message:String(m)});return true});
