const crypto=require('crypto');
const ALPHABET='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
function isTronAddress(a){if(typeof a!=='string'||!/^[T][1-9A-HJ-NP-Za-km-z]{33}$/.test(a))return false;let n=0n;for(const c of a){const i=ALPHABET.indexOf(c);if(i<0)return false;n=n*58n+BigInt(i)}const h=n.toString(16).padStart(50,'0');const payload=Buffer.from(h,'hex');if(payload.length!==25||payload[0]!==0x41)return false;const body=payload.subarray(0,21),sum=payload.subarray(21);const h1=crypto.createHash('sha256').update(body).digest();const h2=crypto.createHash('sha256').update(h1).digest();return sum.equals(h2.subarray(0,4));}
function validatePermission(p,label){if(!p||typeof p!=='object')throw Error(`${label} invalid`);const type=Number(p.type);if(![0,2].includes(type))throw Error(`${label} type invalid`);if(type===0&&Number(p.id||0)!==0)throw Error(`${label} owner id must be 0`);if(type===2&&(p.id!=null&&(Number(p.id)<2||Number(p.id)>9)))throw Error(`${label} active id must be 2-9`);if(!Array.isArray(p.keys)||p.keys.length<1||p.keys.length>5)throw Error(`${label}.keys must contain 1-5 keys`);const seen=new Set();let sum=0;for(const k of p.keys){if(!isTronAddress(k.address))throw Error(`${label} contains invalid address`);const a=k.address.toLowerCase();if(seen.has(a))throw Error(`${label} contains duplicate address`);seen.add(a);const w=Number(k.weight);if(!Number.isInteger(w)||w<=0)throw Error(`${label} contains invalid weight`);sum+=w}const th=Number(p.threshold);if(!Number.isInteger(th)||th<=0||sum<th)throw Error(`${label} threshold unreachable`);if(Buffer.byteLength(String(p.permission_name||''),'utf8')>32)throw Error(`${label} permission_name too long`);if(type===2&&!/^[0-9a-fA-F]{64}$/.test(String(p.operations||'')))throw Error(`${label} operations invalid`);if(p.parent_id!=null&&Number(p.parent_id)!==0)throw Error(`${label} parent_id must be 0`);}
function validateTarget(p,signers){if(!p||typeof p!=='object')throw Error('proposedPermission required');validatePermission(p.owner,'owner');if(Number(p.owner.type)!==0||Number(p.owner.id||0)!==0)throw Error('owner must be type 0/id 0');if(!Array.isArray(p.actives)||p.actives.length<1||p.actives.length>8)throw Error('actives must contain 1-8 permissions');p.actives.forEach((x,i)=>{validatePermission(x,`active ${i+1}`);if(Number(x.type)!==2)throw Error(`active ${i+1} must have type 2`)});if(!Array.isArray(signers)||signers.length!==2)throw Error('exactly two signers required');const s=signers.map(String);if(s[0].toLowerCase()===s[1].toLowerCase())throw Error('A/B cannot be same address');s.forEach(x=>{if(!isTronAddress(x))throw Error('invalid signer address')});const targetKeys=p.owner.keys.map(k=>String(k.address).toLowerCase());if(!targetKeys.includes(s[0].toLowerCase())||!targetKeys.includes(s[1].toLowerCase()))throw Error('target Owner must contain both A/B signers');for(const a of p.actives){const keys=a.keys.map(k=>String(k.address).toLowerCase());if(!keys.includes(s[0].toLowerCase())||!keys.includes(s[1].toLowerCase()))throw Error('target Active permissions must contain both A/B signers');}return true;}
function hasOperation(p,id){if(!p||typeof p.operations!=='string'||!/^[0-9a-fA-F]{64}$/.test(p.operations))return false;const b=Buffer.from(p.operations,'hex'),i=Math.floor(id/8);return i<b.length&&(b[i]&(1<<(id%8)))!==0;}
function currentOwnerAllows(owner,a,b){if(!owner)throw Error('current owner permission missing');const find=x=>Number((owner.keys||[]).find(k=>String(k.address).toLowerCase()===String(x).toLowerCase())?.weight||0);const aw=find(a),bw=find(b),th=Number(owner.threshold);if(aw<=0||bw<=0)throw Error('A/B must both be current Owner signers');if(aw+bw<th)throw Error(`A+B current Owner weight insufficient: ${aw}+${bw} < ${th}`);return{aWeight:aw,bWeight:bw,threshold:th};}
function incomingNativeTransfer(tx,watched){return !!tx&&tx.type==='TransferContract'&&String(tx.to||'').toLowerCase()===String(watched||'').toLowerCase()&&String(tx.from||'').toLowerCase()!==String(watched||'').toLowerCase()&&/^[0-9a-fA-F]{64}$/.test(String(tx.txID||''))&&Number.isSafeInteger(Number(tx.amountSun))&&Number(tx.amountSun)>0;}
function id(){return `REQ-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(5).toString('hex').toUpperCase()}`}
module.exports={isTronAddress,validatePermission,validateTarget,hasOperation,currentOwnerAllows,incomingNativeTransfer,id};
