const {Pool}=require('pg');
const pool=new Pool({connectionString:process.env.DATABASE_URL});
const TERMINAL=new Set(['COMPLETED','FAILED','REJECTED','EXPIRED']);
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS requests(request_id text primary key,target_address text not null,source_type text not null,created_by text,trigger_txid text,trigger_recipient text,proposed_permission jsonb not null,signer_addresses jsonb not null,status text not null,signatures jsonb not null default '[]',tx_id text,created_at timestamptz not null,updated_at timestamptz not null); CREATE UNIQUE INDEX IF NOT EXISTS uq_trigger ON requests(trigger_txid) WHERE trigger_txid IS NOT NULL; CREATE TABLE IF NOT EXISTS audit_log(id bigserial primary key,request_id text,action text not null,actor text,details jsonb,created_at timestamptz not null); CREATE TABLE IF NOT EXISTS settings(k text primary key,v text not null);`)}
async function audit(requestId,action,actor,details={}){await pool.query('INSERT INTO audit_log(request_id,action,actor,details,created_at) VALUES($1,$2,$3,$4,NOW())',[requestId,action,actor,details])}
async function createRequest(r){const q=`INSERT INTO requests(request_id,target_address,source_type,created_by,trigger_txid,trigger_recipient,proposed_permission,signer_addresses,status,signatures,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'PENDING','[]',NOW(),NOW()) RETURNING *`;const v=[r.requestId,r.targetAddress,r.sourceType,r.createdBy||null,r.triggerTxID||null,r.triggerRecipient||null,r.proposedPermission,r.signerAddresses];const out=await pool.query(q,v);await audit(r.requestId,'REQUEST_CREATED',r.createdBy||'SYSTEM',{sourceType:r.sourceType,targetAddress:r.targetAddress,triggerTxID:r.triggerTxID||null});return out.rows[0]}
async function getRequest(requestId){const r=await pool.query('SELECT * FROM requests WHERE request_id=$1',[requestId]);return r.rows[0]||null}
async function pending(address){const r=await pool.query("SELECT * FROM requests WHERE lower(target_address)=lower($1) AND status IN ('PENDING','SIGNING','BROADCAST') ORDER BY created_at",[address]);return r.rows}
async function addSignature(requestId,sig){const client=await pool.connect();try{await client.query('BEGIN');const r=(await client.query('SELECT * FROM requests WHERE request_id=$1 FOR UPDATE',[requestId])).rows[0];if(!r)throw Error('Request not found');if(TERMINAL.has(r.status))throw Error(`Request is ${r.status}`);const allowed=(r.signer_addresses||[]).map(String).map(x=>x.toLowerCase());if(!allowed.includes(String(sig.address).toLowerCase()))throw Error('Signer is not an authorized A/B address');const ss=Array.isArray(r.signatures)?r.signatures:[];if(ss.some(x=>String(x.address).toLowerCase()===String(sig.address).toLowerCase()))throw Error('Signer already submitted');if(ss.length&&String(ss[0].txID).toLowerCase()!==String(sig.txID).toLowerCase())throw Error('All A/B signatures must belong to the same transaction');if(!/^[0-9a-fA-F]{130}$/.test(String(sig.signature||'')))throw Error('Invalid signature format');if(!/^[0-9a-fA-F]{64}$/.test(String(sig.txID||'')))throw Error('Invalid txID');ss.push({address:sig.address,signature:sig.signature,txID:sig.txID,createdAt:sig.createdAt||new Date().toISOString()});const u=await client.query("UPDATE requests SET signatures=$2,status='SIGNING',updated_at=NOW() WHERE request_id=$1 RETURNING *",[requestId,JSON.stringify(ss)]);await client.query('COMMIT');await audit(requestId,'SIGNATURE_SUBMITTED',sig.address,{txID:sig.txID});return u.rows[0]}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
async function setStatus(requestId,status,actor,details={}){if(status==='COMPLETED')throw Error('COMPLETED requires chain verification endpoint');const u=await pool.query('UPDATE requests SET status=$2,updated_at=NOW() WHERE request_id=$1 AND status NOT IN (\'COMPLETED\',\'FAILED\',\'REJECTED\',\'EXPIRED\') RETURNING *',[requestId,status]);if(!u.rows[0])throw Error('Request not found or terminal');await audit(requestId,'STATUS_'+status,actor,details);return u.rows[0]}
async function completeVerified(requestId,txId,details){const u=await pool.query("UPDATE requests SET status='COMPLETED',tx_id=$2,updated_at=NOW() WHERE request_id=$1 AND status='BROADCAST' RETURNING *",[requestId,txId]);if(!u.rows[0])throw Error('Request must be BROADCAST before verified completion');await audit(requestId,'CHAIN_VERIFIED_COMPLETED','CHAIN_VERIFIER',{txId,details});return u.rows[0]}
async function markBroadcast(requestId,txId,actor){const u=await pool.query("UPDATE requests SET status='BROADCAST',tx_id=$2,updated_at=NOW() WHERE request_id=$1 AND status IN ('SIGNING','BROADCAST') RETURNING *",[requestId,txId]);if(!u.rows[0])throw Error('Request must be SIGNING/BROADCAST before broadcast is recorded');await audit(requestId,'BROADCAST_RECORDED',actor,{txId});return u.rows[0]}
async function triggerExists(txid){const r=await pool.query('SELECT * FROM requests WHERE trigger_txid=$1',[txid]);return r.rows[0]||null}
module.exports={pool,init,audit,createRequest,getRequest,pending,addSignature,setStatus,completeVerified,markBroadcast,triggerExists};
